/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Settings;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import view.components.RoundedBorders;

/**
 *
 * @author polilxd
 */
public class SettingsView extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    public SettingsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JPanel();
        roundedInnePanel = new view.components.RoundedBorders();
        txtDeleteData2 = new javax.swing.JLabel();
        txtTheme = new javax.swing.JLabel();
        txtMethod = new javax.swing.JLabel();
        txtDeleteData = new javax.swing.JLabel();
        btnDeleteData = new javax.swing.JButton();
        cbmPriority = new javax.swing.JComboBox<>();
        btnDarkTheme = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(130, 156, 188));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1037, 714));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeadPanel.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Configuración");

        javax.swing.GroupLayout HeadPanelLayout = new javax.swing.GroupLayout(HeadPanel);
        HeadPanel.setLayout(HeadPanelLayout);
        HeadPanelLayout.setHorizontalGroup(
            HeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(800, Short.MAX_VALUE))
        );
        HeadPanelLayout.setVerticalGroup(
            HeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        add(HeadPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1020, -1));

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setOpaque(false);

        txtDeleteData2.setText("Esta opcion eliminará todas las notas guardadas");
        roundedInnePanel.add(txtDeleteData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtTheme.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTheme.setText("Tema oscuro");
        roundedInnePanel.add(txtTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txtMethod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMethod.setText("Método para priorizar notas");
        roundedInnePanel.add(txtMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtDeleteData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDeleteData.setText("Borrar datos");
        roundedInnePanel.add(txtDeleteData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        btnDeleteData.setBackground(new java.awt.Color(254, 91, 107));
        btnDeleteData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteData.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteData.setText("Borrar datos ");
        btnDeleteData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(112, 112, 112), 1, true));
        btnDeleteData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedInnePanel.add(btnDeleteData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 130, 40));

        cbmPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prioridad", "Fecha" }));
        cbmPriority.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbmPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmPriorityActionPerformed(evt);
            }
        });
        roundedInnePanel.add(cbmPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnDarkTheme.setText("Desactivado");
        btnDarkTheme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        roundedInnePanel.add(btnDarkTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(roundedInnePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addComponent(roundedInnePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1020, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void cbmPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmPriorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmPriorityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JRadioButton btnDarkTheme;
    private javax.swing.JButton btnDeleteData;
    private javax.swing.JComboBox<String> cbmPriority;
    private javax.swing.JLabel jLabel5;
    private view.components.RoundedBorders roundedInnePanel;
    private javax.swing.JLabel txtDeleteData;
    private javax.swing.JLabel txtDeleteData2;
    private javax.swing.JLabel txtMethod;
    private javax.swing.JLabel txtTheme;
    // End of variables declaration//GEN-END:variables
    
    public JRadioButton getBtnDarkTheme() {
        return btnDarkTheme;
    }

    public JButton getBtnDeleteData() {
        return btnDeleteData;
    }

    public JComboBox<String> getCbmPriority() {
        return cbmPriority;
    }

    public RoundedBorders getRoundedInnePanel() {
        return roundedInnePanel;
    }

    public JLabel getTxtDeleteData() {
        return txtDeleteData;
    }

    public JLabel getTxtDeleteData2() {
        return txtDeleteData2;
    }

    public JLabel getTxtMethod() {
        return txtMethod;
    }

    public JLabel getTxtTheme() {
        return txtTheme;
    }

    

}
